# Generated by Django 2.2.3 on 2019-07-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
