# Generated by Django 2.2.3 on 2019-07-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=4)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
