# Generated by Django 2.2.3 on 2019-07-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
