# Generated by Django 2.2.3 on 2019-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15)),
                ('port', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=3)),
                ('agent', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
