# Generated by Django 2.2.3 on 2019-07-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keterangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15)),
                ('keterangan', models.CharField(max_length=5)),
            ],
        ),
    ]
